/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Herica Marcionilia
 */
public class tela_inicial extends javax.swing.JFrame {

    /**
     * Creates new form tela_inicial
     */
    public tela_inicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        instrumentos = new javax.swing.JButton();
        vestuário = new javax.swing.JButton();
        eletronicos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        instrumentos.setBackground(new java.awt.Color(255, 102, 204));
        instrumentos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        instrumentos.setText("INSTRUMENTOS");
        instrumentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instrumentosActionPerformed(evt);
            }
        });
        getContentPane().add(instrumentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 220, 150, -1));

        vestuário.setBackground(new java.awt.Color(255, 102, 204));
        vestuário.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        vestuário.setText("VESTUÁRIO");
        vestuário.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vestuárioActionPerformed(evt);
            }
        });
        getContentPane().add(vestuário, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 160, 150, -1));

        eletronicos.setBackground(new java.awt.Color(255, 102, 204));
        eletronicos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        eletronicos.setText("ELETRÔNICOS");
        eletronicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eletronicosActionPerformed(evt);
            }
        });
        getContentPane().add(eletronicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 100, 150, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("MENU");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 40, 80, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Herica Marcionilia\\Desktop\\sistema_UNIVERSE\\menu0.1.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, -30, 290, 380));

        fundo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Herica Marcionilia\\Desktop\\sistema_UNIVERSE\\tela_inicial0.1.png")); // NOI18N
        getContentPane().add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eletronicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eletronicosActionPerformed
        // TODO add your handling code here:
        tela1 te = new tela1();
        te.setVisible(true);
        dispose();
    }//GEN-LAST:event_eletronicosActionPerformed

    private void vestuárioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vestuárioActionPerformed
        // TODO add your handling code here:
        tela2 te = new tela2();
        te.setVisible(true);
        dispose();
    }//GEN-LAST:event_vestuárioActionPerformed

    private void instrumentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instrumentosActionPerformed
        // TODO add your handling code here:
        tela3 te = new tela3();
        te.setVisible(true);
        dispose();
    }//GEN-LAST:event_instrumentosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela_inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela_inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela_inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela_inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela_inicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton eletronicos;
    private javax.swing.JLabel fundo;
    private javax.swing.JButton instrumentos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton vestuário;
    // End of variables declaration//GEN-END:variables
}
